export const orderProducts = [
  {
    id: 1,
    name: "AMVDII Potrait Camelot xx",
    type: "Mens Fashion",
    product_id: "GC-102453",
    owner: "Taylor Mason",
    price: "11120.00",
    size: "XXL",
    color: "Brown",
    qty: "1",
  },
  {
    id: 2,
    name: "AMVDII Potrait Camelot xx",
    type: "Mens Fashion",
    product_id: "GC-102453",
    owner: "Taylor Mason",
    price: "11120.00",
    size: "XXL",
    color: "Brown",
    qty: "1",
  },
  {
    id: 3,
    name: "AMVDII Potrait Camelot xx",
    type: "Mens Fashion",
    product_id: "GC-102453",
    owner: "Taylor Mason",
    price: "11120.00",
    size: "XXL",
    color: "Brown",
    qty: "1",
  },
];
